# Generated by Django 5.0.3 on 2024-03-12 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="follower_set",
        ),
        migrations.RemoveField(
            model_name="user",
            name="following_set",
        ),
    ]
