# Generated by Django 5.0.3 on 2024-03-12 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_avatar_remove_user_follower_set_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
